# Generated by Django 4.2.1 on 2023-05-31 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Websp', '0006_alter_offerboth_amazon_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('flipkart_name', models.TextField(max_length=500)),
                ('flipkart_price', models.IntegerField()),
                ('flipkart_mrp', models.IntegerField()),
                ('flipkart_offer', models.TextField(max_length=50)),
                ('flipkart_star', models.IntegerField()),
                ('flipkart_rating', models.TextField(max_length=50)),
                ('flipkart_avail', models.TextField(max_length=50)),
                ('flipkart_stock', models.TextField(max_length=50)),
                ('flipkart_note', models.TextField(max_length=50)),
                ('buyprice', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(default='Not Yet', max_length=50)),
                ('amazon_name', models.TextField(max_length=500)),
                ('amazon_price', models.IntegerField()),
                ('amazon_mrp', models.IntegerField()),
                ('amazon_offer', models.TextField(max_length=50)),
                ('amazon_star', models.IntegerField()),
                ('amazon_rating', models.TextField(max_length=50)),
                ('amazon_avail', models.TextField(max_length=50)),
                ('amazon_stock', models.TextField(max_length=50)),
                ('amazon_note', models.TextField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
